### ISSUE TITLE
help, how to fix 

### ISSUE THREAD

**Issue by tboss12310** [aprilahijriyan/w3brute#2]
Traceback (most recent call last):
  File "/home/truen/w3brute/lib/core/common.py", line 246, in openFile
    return f.read()
  File "/usr/lib/python2.7/codecs.py", line 686, in read
    return self.reader.read(size)
  File "/usr/lib/python2.7/codecs.py", line 492, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

**Comment by apylib** [comment]
@tboss12310 What type of file did you enter?

**Comment by aprilahijriyan** [comment]
you only need to enter the file extension (.txt) or (.zip). See file [README.md](https://github.com/aprilahijriyan/w3brute/blob/master/README.md#usage).
